### ISSUE TITLE
environment.yml file is not downloaded while cloning the respository

### ISSUE THREAD

**Issue by Tan12uja** [microsoft/CameraTraps#133]
hey, why the yml files are not downloaded while cloning the respository

**Comment by yangsiyu007** [comment]
Hi @Tan12uja , I just cloned the repo again and all the files are there. How did you download/clone the repo?

**Comment by yangsiyu007** [comment]
Hi @Tan12uja, are you still having this issue? If we don't hear back from you in a week we'll be closing this issue :)

**Comment by Tan12uja** [comment]
Hey,

so sorry, I did not reply.

Yes, the file did not get downloaded again. But, I created a similar one on
my python IDE.
Since, I got busy on some other project - completely, lost the track of
this.

Thanks!
Tanuja
