### ISSUE TITLE
Confused about language for how to set-up a local batch process with the pre-trained Megadetector_v3

### ISSUE THREAD

**Issue by Jonathan-Gore** [microsoft/CameraTraps#140]
Hi!

I am confused about how to initiate the batch processing functionality of the megadetector. I've now successfully called the single image detection script, but am not completely understanding what phrasing to use when designating a multiple images to be sifted through the run_tf_detector_batch.py

I'm new to all of this, I've learned what a json file is and see that designating one is necessary for the batch process. Would someone be able to point me in the right direction for how to phrase the command to designate multiple images to the batch process script?

Thanks for your time!

edit: Correction, I now understand the purpose of the json file and it's role with using the visualization tool. My main confusion is how do you communicate to the script that an entire directory of images is to be classified as opposed to just one.

**Comment by Jonathan-Gore** [comment]
Oh geez, major user error on my end. Will try to keep future questions less dumb and more infrequent. Issue closed.

**Comment by yangsiyu007** [comment]
Glad you were able to figure this out @Jonathan-Gore! Yes, the `image_file` argument can be path to a directory as explained in its help text, but yes, it is a confusing argument name!
