### ISSUE TITLE
make_classification_dataset with custom train/test split

### ISSUE THREAD

**Issue by davidwhealey** [microsoft/CameraTraps#153]
Thanks for making this great repo!  

I love that make_classification_dataset.py allows you to crop images using the megadetector and create the tfrecords at the same time.  One thing that has not been clear to me is how to specify a specific train/test split rather than having the script automatically split across locations.

Is there a way to do this?

**Comment by yangsiyu007** [comment]
Hi there! Unfortunately that's not possible right now (we're looking to change this in the summer), but as a workaround, you can run the script on your train set and set the split ratio to have zero test images (to create the training tfrecords), and then again on the test set, specifying for there to be zero training images (to create the test tfrecords).

**Comment by davidwhealey** [comment]
I was getting a nonempty test.json even with a zero training image fraction, which I did not investigate further.  But what I ended up doing was to create custom train.json and test.json files in the cropped dataset, then ran data_management/tfrecords/create_tfrecords_from_coco.py   That appears to have worked.
