### ISSUE TITLE
Batch inference with classifier?

### ISSUE THREAD

**Issue by davidwhealey** [microsoft/CameraTraps#155]
What is the appropriate way to do batch inference using a trained classifier?  The classifier documentation lists three methods:

1. predict_image.py
2. detect_and_predict_image.py
3. generate_sample_predictions.py

The first appears not to support batch inference.  #2 and #3 do batch inference, but running each of them resulted in the entire data set attempting to be loaded into memory.  What is the correct way to perform inference on a large number of images using this repo?

**Comment by agentmorris** [comment]
Wow, we really worked hard to hide the script that I would actually recommend using in this case, which is none of those three... :)

If you are planning to run both our detector and a classifier trained with our recommended pipeline, I would do this in two stages, with:

- [run_tf_detector_batch.py](https://github.com/microsoft/CameraTraps/blob/master/detection/run_tf_detector_batch.py) to run the detector
- [apply_classifier_single_node.py](https://github.com/microsoft/CameraTraps/blob/master/classification/api_apply_classifier_single_node.py) to run the classifier on the crops produced by the detector

The reason you didn't see the latter script before is that it was all by itself in a folder called "api", I just moved it out of that folder.

This two-step process is exactly what we did, for example, to generate these results;

- [Snapshot Serengeti season 7 classification results](http://dolphinvm.westus2.cloudapp.azure.com/data/snapshot-serengeti/s7-eval/postprocessing-classification-gt/)

Let us know if that helps!

-Dan
