### ISSUE TITLE
Failed to load the native TensorFlow runtime.

### ISSUE THREAD

**Issue by SarahDal** [microsoft/CameraTraps#178]
I'm a little familiar with Python and Anaconda, and have followed the steps for installation on a windows machine. However, I get the error "Failed to load the native TensorFlow runtime" when I try to  run_tf_detector.py - can anyone point me to where I am going wrong?

**Comment by agentmorris** [comment]
Sorry you're having trouble getting the detector running... a couple questions:

1. Did you use the instructions here:<br/><br/><https://github.com/microsoft/CameraTraps/#machine-learning-scripts><br/><br/>...i.e., did you run:<br/><br/>`conda env create --file environment-detector.yml`

2. If so, did you run:<br/><br/>`conda activate cameratraps-detector`<br/><br/> ...before running the detector script?  

3. Do you have a GPU on your computer?

**Comment by agentmorris** [comment]
Closing this issue for lack of response from the OP; feel free to contact us at cameratraps@microsoft.com if you're still unable to resolve this issue.  Thanks!
