### ISSUE TITLE
ModuleNotFoundError: No module named 'ct_utils'

### ISSUE THREAD

**Issue by rasanderson** [microsoft/CameraTraps#191]
Hello
I'm new to using Tensorflow and Python, and have possibly made a silly mistake, but I keep getting this error when I try and run the run_tf_detector.py script:

python CameraTraps/detection/run_tf_detector.py md_v4.1.0.pb --image_file IMG0027.JPG
Traceback (most recent call last):
  File "CameraTraps/detection/run_tf_detector.py", line 54, in <module>
    from ct_utils import truncate_float
ModuleNotFoundError: No module named 'ct_utils'

Setup is:
Ubuntu 18.04
python --version
Python 3.6.8

echo $PYTHONPATH
\~/ml/microsoft_mega/CameraTraps;\~/ml/microsoft_mega/ai4eutils
which was created via
export PYTHONPATH="\~/ml/microsoft_mega/CameraTraps;~/ml/microsoft_mega/ai4eutils"
so it is possible I've made a mistake here as the instructions are for Windows.

I'm not using Anaconda, but a Python virtual environment. Tensorflow and other pip libraries all installed without problems.
Many thanks, and apologies if I've overlooked something simple.
Roy

**Comment by persts** [comment]
@rasanderson looks like you have an issue with your PYTHONPATH the semicolon should be a colon

~/ml/microsoft_mega/CameraTraps:~/ml/microsoft_mega/ai4eutils

**Comment by rasanderson** [comment]
Thank you very much @persts as that has solved the problem (silly error on my part). Initially it still didn't run (I'd stupidly installed Tensorflow 2.0 instead of 1.13.1) but after downgrading it ran. The script showed a number of messages along the lines of: 

Failed to run optimizer ArithmeticOptimizer, stage RemoveStackStridedSliceSameAxis node Preprocessor/map/while/ResizeToRange/strided_slice_3. Error: Pack node (Preprocessor/map/while/ResizeToRange/stack_2) axis attribute is out of bounds: 0

Nevertheless, it successfully produced an output image, and correctly detected the animal in the camera trap imagery. Thanks again for your prompt answer and help.
