### ISSUE TITLE
tflite version

### ISSUE THREAD

**Issue by vanheerdena** [microsoft/CameraTraps#209]
Hi, that you for all the work done on this model and for sharing it with freely. I am wanting to use it in a real-time situation i.e. to spot monkeys in my vegetable patch. I was hoping to get it working on a rasp pi 4 with Coral Edge TPU. The Coral can only use tensorflow lite and so I paid someone to try convert the MegaDetector into a version that could run on the Coral TPU but that was unfortunately unsuccessful. My question is where you think there is any change or releasing a version that might run on a pi / Coral TPU / tflite?

**Comment by agentmorris** [comment]
MegaDetector is a pretty large model, and it would be a substantial project to re-target it to run on the Coral Edge.  This is a bigger issue than just TF1 vs. TFLite; it's just larger than I think is practical here.  I might suggest two other approaches, though:

1) Some users have reported success using MegaDetector to generate bounding boxes on a data set of images specific to their own environment (e.g., your garden), then using those bounding boxes to train a much smaller model.  If you want a model just for your garden, this is what I would recommend.

2) About half of the training data we use for training MegaDetector is available publicly at http://lila.science; you might train a model based on that training data.

With either of these approaches, you would be able to use the tools provided specifically for the Coral Edge environment, and I think you would find things to be much less complicated than trying to "bend" the existing MegaDetector model to run in your environment.

Hope that helps!

-Dan

**Comment by vanheerdena** [comment]
Thank you so much for the advice Dan. I'll look into exploring those 2 options!
