### ISSUE TITLE
tensorflow-gpu version

### ISSUE THREAD

**Issue by pbick** [microsoft/CameraTraps#246]
Hello, just a quick question about the supported tensorflow-gpu version. I am having installation issues with version 1.13.1 and was wondering if there is a more recent version that works, or if it must necessarily be 1.13.1. Thanks!

**Comment by agentmorris** [comment]
1.14 and 1.15 should work too.  Also, though we haven't tested it extensively, folks who have tried TF2 have had success, they just had to replace “import tensorflow as tf” with “import tf.compat.v1 as tf”.

**Comment by agentmorris** [comment]
The above modifications are no longer necessary; the main branch now assumes that TF2 is installed, and the relevant scripts always import tensorflow.compat.v1.
