### ISSUE TITLE
MegaDetector crashes on VM instance

### ISSUE THREAD

**Issue by pbick** [microsoft/CameraTraps#247]
I'm trying to run the MegaDetector over some images on a GCP VM instance with a Tesla T4 GPU. I created a conda virtual environment using the environment-detector.yml file with the tensorflow-gpu version set to 1.13.1, and I am trying to run the run_tf_detector_batch.py script as instructed in the MegaDetector page. However, the process crashes while processing the first image (below is a screenshot of my terminal window when that happens):

<img width="913" alt="Screen Shot 2021-03-25 at 1 34 27 AM" src="https://user-images.githubusercontent.com/39545188/112500225-93243d00-8d5e-11eb-98c7-1d3679667736.png">

I've tried to trace the program but haven't been able to figure out what the issue is. Any idea why this might be happening and how to solve it? Thanks!

**Comment by pbick** [comment]
Update: if I change the tensorflow-gpu version to 1.14.0, the last error ("axis attribute is out of bounds") no longer happens, but the memory errors persists and the process still is killed.

**Comment by agentmorris** [comment]
Sorry you're having trouble with MegaDetector... a couple questions:

* In the new scenario, with TF 1.14, do you see "...exceeds 10% of system memory", then just "Killed"?  There's no error before "Killed"?
* Confirm that you are not running inside Docker or any other virtualized environment?
* When all else fails, try TF random versions... if it's not too much trouble, do you mind trying TensorFlow 1.15 also?

**Comment by pbick** [comment]
I changed the tensorflow-gpu version to 1.15.0 and it seems like it worked! Thanks!

**Comment by agentmorris** [comment]
Glad we got it running!

"Do random stuff until it works": still the most reliable solution to technology problems.
