### ISSUE TITLE
I am not properly able to understand the real time api docs , can someone help me out? 

### ISSUE THREAD

**Issue by a-ma-n** [microsoft/CameraTraps#258]

**Comment by a-ma-n** [comment]
I wanted to use the synchronous api, but in the class names folder I'm using the megadetector model what class names should I provide its not clearly mentioned in mega detector also

**Comment by agentmorris** [comment]
Thanks for your interest!  Documentation for the synchronous API is [here](https://aiforearth.portal.azure-api.net/docs/services/ai-for-earth-camera-trap-detection-api/operations/post-detect).  From the documentation:

> Each detection is an array, formatted as [ymin, xmin, ymax, xmax, confidence, category], where the first four floats are the relative coordinates of the bounding box. category is one of 1 (animal), 2 (person), or 3 (vehicle).

The synchronous API requires an API key; email aiforearthapi@microsoft.com to request a key.  We will ask a few questions about your use case to help you assess whether the API is the right approach, vs. running the MegaDetector model some other way.

**Comment by a-ma-n** [comment]
Thank you so much!
