### ISSUE TITLE
Is the batch processing API and the  real-time API running the same classifiers ?

### ISSUE THREAD

**Issue by krasi-georgiev** [microsoft/CameraTraps#260]
Looking into classifying some thermal images to filter out empty images and roughly label when there is are different objects in the pictures. Will process around 3000 images per day and need to label 3-4 different categories - empty , animal, human

Wondering if the live web API or the batch processing would be a better option?
The readme says that the web API runs species classifiers so wondering if they are the same for the batch processing

Also do you use some public discord or slack?

**Comment by agentmorris** [comment]
Thanks for your interest!  A few points...

1) Unfortunately I suspect that our MegaDetector model will not be very helpful for thermal images.  It has never seen any thermal images in training, and machine learning doesn't like surprises.  By all means, give it a shot, but that's likely very different than what our model is used to seeing.

2) 99% of our users don't use either of our APIs (users typically either run MegaDetector on their own, or work with us to run large batches on the cloud), so in fact we've just deprecated both API endpoints.  The code remains open-source and we will work with users who want to deploy their own instances, but we won't be maintaining live endpoints for either API.

3) That said, neither API supported species classification, both just ran the same MegaDetector model that's publicly accessible.  Species classification typically requires some bespoke work for new ecosystems.

Let us know more about your scenario and we'll find out the best way to support you!  At 3000 images per day (which is not a heavy volume), you have lots of options.  We can discuss here, or you can [email us](mailto:cameratraps@lila.science).

We don't use Slack per se, but we can discuss here, by email, or - if you want lots of community input, especially if you decide to train species classification models for your ecosystem - we also hang out at the [AI for Conservation Slack channel](https://aiforconservation.slack.com).

**Comment by krasi-georgiev** [comment]
thanks, yes I would like to join the channel, but there is no option to register, just to login. If you can please send me an invite 
krasi@arribada.org

**Comment by agentmorris** [comment]
Done.  See you there!
