### ISSUE TITLE
pretrained weights for megadetector v5?

### ISSUE THREAD

**Issue by rbavery** [microsoft/CameraTraps#275]
Thanks for continuing to maintain this awesome set of tools! My question is about where to find the latest release. I see megadetector v5 referenced here: https://github.com/microsoft/CameraTraps/blob/main/detection/README.md

But the latest release is for 4.1 https://github.com/microsoft/CameraTraps/releases/tag/v4.1

Are the weights available somewhere else other than the release page? We might be using Megadetector soon in addition to https://github.com/microsoft/SpeciesClassification to detect people, mountain lions, foxes, coyotes, and deer and I was looking to use the most up to date models published here.

**Comment by agentmorris** [comment]
MegaDetector v5 is coming soon... stay tuned!  Hopefully weeks, not months.

And FWIW I wouldn't recommended the species classification model you linked you above, and I say this even as part of the team that made it. :). It's both out of date (and therefore very hard to run against current versions of PyTorch) and very limited in what it can be used for.  It was trained on citizen science data and Web images, so definitively not suited for camera trap data (I'm assuming you're working with camera trap data based on the fact that you're asking about MegaDetector).

But if we can help you get MegaDetector up and running in your workflow, let us know!  You can find us here or at cameratraps@lila.science.
