### ISSUE TITLE
Detection Issues

### ISSUE THREAD

**Issue by TobiasHabesha** [microsoft/CameraTraps#276]
Dear authors of MegaDetector, 

I would be very grateful, if you could help me and my colleagues with a very persistent issue:
We applied MegaDetector (run_tf_detector_batch.py) for a large amount of camera trap imagery. Yet we noticed that for many cases, the locations of the individual bounding boxes, stored in the resulting JSON-file, do not represent the animals’ actual position within the image. Thus, we ran the test version (run_tf_detector.py) for a collection of images. Yet the bounding boxes in the resulting “..._detections”-images just matched perfectly with the animal’s location. Consequently, we performed the batch-version on folders only containing one of these test images and the resulting JSON-files contained the exact same values as after the first run while still not matching the animals position. 
We performed these steps on several different PCs (computers and laptops) as well as with different operating systems (Ubuntu and Windows). However, the issue persists. 

We would be extremely grateful for your advice and help.

Best regards, 
Tobias Pelchen (e-mail: tobias.pelchen@lwf.bayern.de)

[detection issue.pdf](https://github.com/microsoft/CameraTraps/files/7980092/detection.issue.pdf)

**Comment by agentmorris** [comment]
Very odd... we had one other user report exactly the same behavior recently (incorrect results in the batch script, correct results in the non-batch script), and when they sent us some sample images, we were unable to reproduce the issue.  

First, are you using the "use_image_queue" option in run_tf_detector_batch.py?  We haven't directly observed any issues with this option, but the most recent set of changes added this option so there could be a regression hiding here, and it is a threading-related change, so regressions can be sneaky.

Next, two suggestions:

- If you are able to share a couple of the images where you are getting incorrect results, can you email cameratraps@lila.science with those images so we can try to reproduce the issue?  And also confirm that you still observe this issue when you *only* run on those images?
- Can you try rolling the repo back to a commit from a few months ago, e.g. [this one](https://github.com/microsoft/CameraTraps/commit/9ba3acc2b298ddfb2f9540b27725dcab5396b90a) and try again?  There were some changes to run_tf_detector_batch.py in December that shouldn't have impacted this, and we haven't been able to reproduce this issue, but let's double-check.

Thanks.

**Comment by agentmorris** [comment]
Also, were *all* images impacted, or just some?  If it was just some images, was it the same images on every computer you tried?

**Comment by TobiasHabesha** [comment]
Dear Mr. Morris,  

We ran the detector on two different devices and the results were the same, exactly the same images were affected and also the values were the same throughout the different runs.  

I am not fully assured, if we applied the "use_image_queue", here is a typical example of how I ran the detector:  

**Preparation**: 

> conda activate cameratraps-detector 
> 
> cd c:\git 
> 
> set PYTHONPATH=c:\git\cameratraps;c:\git\ai4eutils

 

**Test-run:** 

> python c:\git\cameratraps\detection\run_tf_detector.py c:\git\md_v4.1.0.pb --image_file c:\Users\Tobia\Documents\I_00017b.jpg 

**Batch-run:** 

> python c:\git\cameratraps\detection\run_tf_detector_batch.py c:\git\md_v4.1.0.pb c:\Users\Tobia\Pictures\VF_12 c:\Users\Tobia\Pictures\VF_12\out_Y.json --recursive 


I sent the images to the cameratraps@lila.science, as you recommended.

is the format of the bounding box information as stored in the JSON file like beneath?

> [x_min, y_min, width of the bb, height of the bb]

**Comment by TobiasHabesha** [comment]
Hello, I think we solved the problem, 
the format of the bounding box information is:

> [x_min, y_min, width of the bb, height of the bb]

By y_min + height of the bb you will get y_max. 
All works well now and the lines match perfectly with the bounding boxes drwan by the test run.

I am very sorry for  any inconvenience caused.

**Comment by agentmorris** [comment]
Great!  No inconvenience at all, always better to ask if you think there might be a bug.  Let us know if you have any other questions!

**Comment by totoadel** [comment]
@TobiasHabesha you save my day with this answer
