### ISSUE TITLE
Megadetector v5 release date?

### ISSUE THREAD

**Issue by syntherick** [microsoft/CameraTraps#280]
Hey. I'm curious about when will the pytorch code and weights for Megadetector v5 be released. I have seen reference about it [here](https://github.com/microsoft/CameraTraps/blob/main/detection/README.md)

**Comment by percybolmer** [comment]
I second this question

**Comment by agentmorris** [comment]
Thanks for your interest!  We are still planning to release a v5 model, and you've likely noticed that our tooling has been updated to accommodate PyTorch-based models.  But we're still working on QA and we're selecting from a few release candidates, so we don't have a final release date.  Stay tuned!

**Comment by totoadel** [comment]
@agentmorris thank you, it works

**Comment by totoadel** [comment]
please close the issue

**Comment by agentmorris** [comment]
MDv5 will be released in the next ~day or two!  Closing this issue so we have one less thing to forget to do. :)
