### ISSUE TITLE
how to get MegaClassifier pretrained model "MegaClassifier"??

### ISSUE THREAD

**Issue by changsub132** [microsoft/CameraTraps#291]
how to download "v0.1_efficientnet-b3_compiled.pt" file?
is it share? or not?

**Comment by agentmorris** [comment]
We have not publicly released any species classification models.  For some use cases, we may be able to share one or more models if you contact us at cameratraps@lila.science, but our classification models are currently targeted for very specific workflows, so we're not sharing them broadly.

Others have used our [classification code](https://github.com/microsoft/CameraTraps/tree/main/classification) as a starting point for training your own classifiers that are relevant to your data; this may be a more practical starting point.

Thanks.

-Dan
