### ISSUE TITLE
model layer structure for frozen training 

### ISSUE THREAD

**Issue by ehallein** [microsoft/CameraTraps#320]
I am training for specific species using a frozen backbone as discussed here: https://docs.ultralytics.com/tutorials/transfer-learning-froze-layers/

I can’t find any documentation on the layer structure for megadetector v5. Is it the same as yolov5 with layers model.0.' - 'model.9 making up the backbone? 

Thanks

**Comment by agentmorris** [comment]
We did no modification to the architecture; MegaDetector is a trained instance of YOLOv5x6.  I can't find a great representation of YOLOv5x6 specifically, but you can visualize the layers with, e.g., [netron.app](https://netron.app).

Hope that helps!

**Comment by ehallein** [comment]
Excellent, knowing the model used gives me the answer.  So did you train the images at 1280 pixels?

**Comment by agentmorris** [comment]
Yes.  More specifically, we trained with --imgsz 1280, which means "set the long side of each image to 1280 and adjust the short side to maintain aspect ratio".  This appears to be standard for YOLOv5x6.
