### ISSUE TITLE
Environment-classifier Installation - ResolvePackageNotFound

### ISSUE THREAD

**Issue by amorell747** [microsoft/CameraTraps#330]
(base) c:\git\cameratraps>conda env update -f environment-classifier.yml --prune
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:
  - accimage

**Comment by agentmorris** [comment]
Oops, the classifier environment has been run almost entirely in Linux, and the "accimage" package is Linux-only.  Fortunately, this package is optional.  I just commented out of environment-classifier.yml, and added optional instructions to install it for Linux users.  The code will work with or without it.  You can either get the latest version of the repo, or you can just comment accimage out of environment-classifier.yml.  Thanks for catching this!
