### ISSUE TITLE
Handling MPO images in separate_detections_into_folders

### ISSUE THREAD

**Issue by aweaver1fandm** [microsoft/CameraTraps#336]
We ran into an issue where separate_detections_into_folders.py was crashing when run with the --render_boxes flag.  The error was essentially that you could not use quality=keep when original image is not JPEG.  All the images we were processing had .JPG as the extension but when we did some digging we found that pil_image.format was MPO and not JPEG.

In our case the trail cameras were capturing stereoscopic images and saving them as .JPG.  According to the Pillow documentation, it both opens and saves such images by using the first image in the sequence, which explains why the detector works fine.  However, the quality flag currently being used to save images (starting at line 386 in separate_detections_into_folders.py) only applies to true JPEG images.

We propose the following changes to that section of code:

```bash
       # Write output with EXIF metadata and quality='keep'
        # but only if the image is format JPEG.  Other image formats such as MPO
        # will fail if quality flag is used
        if exif is not None:
            if pil_image.format == "JPEG":
                pil_image.save(target_path, exif=exif, quality='keep')
            else:
                pil_image.save(target_path, exif=exif)
        else:
            if pil_image.format == "JPEG":
                pil_image.save(target_path, quality='keep')
            else:
                pil_image.save(target_path)
```

With this change in place, the code ran fine and appropriately produced the bounding boxes in the MPO images. 
Since we are not intimately familiar with the full extent of code in the project, similar changes may need to be made elsewhere.

**Comment by agentmorris** [comment]
Good catch, we'll definitely fix this.  I'd like to be able to verify the fix, though, and I don't have an MPO camera trap image to test with.  Would you mind sending links to a couple of images here (maybe one or two with animals, one or two without), or sending to info@lila.science?

I'm also not clear on what the expected behavior is... I'm about 99.4% sure PIL won't write the box to *both* images in the MPO image pair, and I have no idea whether PIL will even write both images out.  Have you verified this?  Does this matter for your use case?  If you're just using these MegaDetector results to sort images, then you'll go back to the original files for stereo analysis, this doesn't matter, but if you're expecting the multi-image format to be properly preserved, this could get a little dicey.

More generally, just out of curiosity, I'm super-interested in why one captures stereo camera trap images.  If you don't mind, it would also be great if you could share a bit more about your use case!

Thanks!

**Comment by aweaver1fandm** [comment]
Some sample images are attached.  I have attached both the original and the result we got including one image that had nothing in it.

As far as specifically MPO images, we  don't specifically need to keep all images that are part of the stereoscopic image.  We're not expecting, nor do we need multi-image format to be properly preserved.

As for why we're capturing stereo images in the first place, the impression I get from the actual researcher doing this work, is it's completely accidental.  They happen to be using some cameras which capture stereo images but get downloaded as JPEG file.  The files open just fine when you click them so the researcher never realized there was a difference.  We only found the difference because the bounding box code failed.  We run megadetector on  Linux  and even when we did something like: ```file myfile.jpg```, on the command-line it said the file is JPEG.  It wasn't until we printed out pil_image.format in the python code that we saw it was in actually in MPO format.

![11210022_empty](https://user-images.githubusercontent.com/55799947/228588293-e56e95a0-c307-4929-92be-1f1bf1c9538b.JPG)
![11210024](https://user-images.githubusercontent.com/55799947/228588296-18dddcec-a793-4a62-a3b4-d04419f20c45.JPG)
![11210024_bounded](https://user-images.githubusercontent.com/55799947/228588298-e8d86511-e525-4121-bea3-744be5fbc0bc.JPG)
![11210065](https://user-images.githubusercontent.com/55799947/228588300-66e183db-9cdd-40b1-b8d0-6378db05cfcc.JPG)
![11210065_bounded](https://user-images.githubusercontent.com/55799947/228588303-f53d2333-2f2b-4027-a084-8f8a49cd6747.JPG)

**Comment by agentmorris** [comment]
All clear, thanks.  I'm a little suspicious that the format is properly preserved when rendered on GitHub; can you send links to the original images, or attach to email to info@lila.science?  Thanks!

**Comment by agentmorris** [comment]
The OP shared images offline, I was able to reproduce and fix, using exactly what the OP suggested.  I verified that everything still works fine for .jpg images.  Thanks for finding this!

(Also, what is that animal?  A raccoon?  A possum?  An undead fox?)

**Comment by aweaver1fandm** [comment]
Dan,

I think it's a possum
