### ISSUE TITLE
class labels significance

### ISSUE THREAD

**Issue by saikatdutta** [microsoft/CameraTraps#34]
Where can I get the mapping between class labels and class names in "run_tf_detector.py" ?

**Comment by yangsiyu007** [comment]
Hi @saikatdutta, please see [experiments/megadetector_v3/label_map.pbtxt](https://github.com/microsoft/CameraTraps/blob/master/detection/experiments/megadetector_v3/label_map.pbtxt) for the class label mapping for the MegaDetector (version 3, to be released shortly; in version 2 there is only one class, 1:animal).

**Comment by saikatdutta** [comment]
OK, but when I ran the code on megadetector_v2, I got some labels other than 1(55,83 etc.). What are those labels actually?

**Comment by yangsiyu007** [comment]
The megadetector was warm started with COCO weights and we left all the layers in, so the output technically has 90 classes (the COCO stuff classes). But the model is only meant to be applied to camera trap photos, and only class 1 (and when we release v2, class 2 as well) should be considered meaningful.
