### ISSUE TITLE
Scripting MegaDetector model v5a 

### ISSUE THREAD

**Issue by r2j2ritson** [microsoft/CameraTraps#340]
Hello, 

I would like to export the MegaDetector model `md_v5a.0.0.pt` as a TorchScript so I can utilize it more freely. It looks like this capability exists in 'yolov5'/ export.py` but I'm having trouble implementing it. Any advice?

**Comment by r2j2ritson** [comment]
Thanks, Dan! This got me on the right track. I'll let you know if I have anymore issues. I noticed someone already put together an R package using the tensorflow .pb models, but since it looks like you have moved on to pytorch I figured I'd give a try to getting the v5 models usable in R.

**Comment by agentmorris** [comment]
If you're referring to this package:

https://github.com/conservationtechlab/animl

...my first thought was also that they're using MDv4, but they report that they've exported MDv5 as a TensorFlow model, so if you want to work in R and you're finding that it's lots of work to wrap MDv5 in R, you may want to check in with them.  There are pros and cons to that approach and I haven't tested the package, so, YMMV.
