### ISSUE TITLE
Missing compiled model file for classification inference

### ISSUE THREAD

**Issue by workhodge1** [microsoft/CameraTraps#352]
I'd like to run inference on my cropped data using the MegaDetector v0.1 model discussed in Step 3 here: https://github.com/microsoft/CameraTraps/tree/main/classification. However, I can not find the model file listed anywhere in the repo.

**Comment by nomoneyExpection** [comment]
do you find the model file now?

**Comment by workhodge1** [comment]
> do you find the model file now?

Not yet. Please give me a heads up if you find it.

**Comment by nomoneyExpection** [comment]
I haven't found it yet, and I have a new problem. After installing it according to its installation environment requirements, run python detection\run_detector.py "c:\megdetector\md_v5a.0.0.pt" --image_file "some_image_file.jpg " --threshold 0.1, the error ModuleNotFoundError: No module named 'md_visualization', do you have a solution?

**Comment by nomoneyExpection** [comment]
The result I see should be that there is no such model. This model is obtained by him based on efficientnet training. There seems to be no big difference in the detection type, and the accuracy has improved a little.
