### ISSUE TITLE
can not find something i need

### ISSUE THREAD

**Issue by nomoneyExpection** [microsoft/CameraTraps#353]
v0.1_efficientnet-b3_compiled.pt

**Comment by aa-hernandez** [comment]
Thank you for your valuable input. We've moved to a new codebase with the release of Pytorch-Wildlife v1.0. The issue you mentioned might not exist anymore or it might be resolved in the new codebase. We encourage you to try the new release [here](https://github.com/microsoft/CameraTraps) and share any further feedback or concerns. If the issue still persists, please let us know through this channel and we will work on it!

If you're still interested in working with the previous version, you can take a look at [Dan Morris' fork](https://github.com/agentmorris/MegaDetector/tree/main). The issue may or may not be resolved in that codebase.
