### ISSUE TITLE
small typo in documentation

### ISSUE THREAD

**Issue by rohilm** [microsoft/CameraTraps#384]
https://github.com/microsoft/CameraTraps   
You can find more information in our documentation.

https://cameratraps.readthedocs.io/en/latest/
Installation

Gradio Interface: Dive into an interactive demo using Gradio, which provides a user-friendly interface for quick demonstrations. [Link to the tutorial](./demo/gradio_demo.ipynb) --> should be ./demo/gradio_demo.py

**Comment by aa-hernandez** [comment]
Hi there,

Thank you for bringing this to our attention!

I'm happy to inform you that the issue has been resolved. We've updated our process, and users are now directed to a new set of instructions under installation.md. This should streamline the installation process and provide clearer guidance.

Best Regards,

Andrés.
