### ISSUE TITLE
Warning occur

### ISSUE THREAD

**Issue by yodaka0** [microsoft/CameraTraps#391]
Thank you create this program.
I use PytorchWldlife for video organize.
Specifically, video clip and run berow
# Performing the detection on the single image
 result = detection_model.single_image_detection(transform(img), img.shape, im_file, conf_thres=threshold)
but 
WARNING: NMS time limit 0.330s exceeded
occur
What is problem?

**Comment by aa-hernandez** [comment]
Hi @yodaka0!
Thank you for submitting this issue! Would you mind sharing a snippet of code to replicate this issue?

**Comment by yodaka0** [comment]
Thank you for your response. It's a bit long, but please take a moment to read through it.
this is my repository
https://github.com/yodaka0/VideoExtractWin/blob/master/image_demo.py

**Comment by zhmiao** [comment]
Hello @yodaka0 , thanks for reporting this. It seems this is a Yolo issue. Here is the link to the original issue: https://github.com/ultralytics/yolov5/issues/7390 

I think if it does not cause actual problem in your code, you can either ignore it or do what the orignal issue suggested by making modifications in the yolo package. 

I will close this issue for now, but please do feel free to reopen this issue if you find the solutions in the original issue doesn't help!

Thank you very much again!
