### ISSUE TITLE
Generate Spectrograms from audio files 

### ISSUE THREAD

**Issue by arky** [microsoft/CameraTraps#442]
Please kindly add function to generate audio spectrograms from variable length audio recordings.  Generation of audio spectrograms and turning them into tensors is the first step in preparing data for adding support for bio-acoustics #441 pytorch wildlife platform.  

Multiple libraries exist to generate these spectrograms such as scipy, librosa, scikit-learn and also individual tools such as sox.

**Comment by zhmiao** [comment]
Hello, @arky, Thanks for creating this issue! Since this issue is directly related to https://github.com/microsoft/CameraTraps/issues/441, we are going to close this one and add information here to the original issue for now. Please feel free to reopen this issue if you feel necessary! Best.
