### ISSUE TITLE
Windows install documentation correction

### ISSUE THREAD

**Issue by DavidNZ27** [microsoft/CameraTraps#458]
### Search before asking

- [X] I have searched the Pytorch-Wildlife [issues](https://github.com/microsoft/CameraTraps/issues) and found no similar bug report.

### Bug

Step 6 in the Windows install document says to run the command "pip install pytorch-wildlife" this command fails as there is no matching distribution. Run "pip install pytorchwildlife" works as per the screenshot in the document however. 

![image](https://github.com/microsoft/CameraTraps/assets/99003872/26e82150-3be2-48fa-87c0-799a1950e553)

![image](https://github.com/microsoft/CameraTraps/assets/99003872/ae8afd2e-f824-4f10-9680-29d913970df9)

### Environment

N/A is in the documentation

### Minimal Reproducible Example

N/A is in the documentation

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by zhmiao** [comment]
Hello @DavidNZ27, thank you very much for reporting this to us! We have fixed the typo in the most recent updates!
