### ISSUE TITLE
Exclude label categories from export

### ISSUE THREAD

**Issue by JaimyvS** [microsoft/CameraTraps#464]
### Search before asking

- [X] I have searched the Pytorch-Wildlife [issues](https://github.com/microsoft/CameraTraps/issues) and found no similar bug report.

### Description

I would like to request the option to exclude certain labels from being exported. I saw that the `pw_utils.save_detection_json` has a `categories` argument, but was not able to figure out if this can be used to specify what categories should be exported.

### Use case

For my use case, I'm using the output of PyTorch-Wildlife to train another model. For this, I only need the animals being detected, not the persons and vehicles. Currently, I'm using a second Python script to filter these out. This works fine, but having the option in the library would be great.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by zhmiao** [comment]
Hello @JaimyvS , thanks for the suggestion! We will add the option in our json indention updates as well!

**Comment by zhmiao** [comment]
Hello @JaimyvS, this issue is addressed with the newest commits! You can update the package through pip and test the new json output functions! Thank you very much again!

**Comment by JaimyvS** [comment]
Awesome, that works great! Thanks for both!
