### ISSUE TITLE
Datasets Details

### ISSUE THREAD

**Issue by 13185742215** [microsoft/CameraTraps#504]
### Search before asking

- [X] I have searched the Pytorch-Wildlife [issues](https://github.com/microsoft/CameraTraps/issues) and found no similar bug report.

### Question

Which animals are identified by the model, how are they named, and can you give pictures and names comparison examples (including each animal species)?

**Comment by zhmiao** [comment]
Hello @13185742215 , thank you very much for reaching out. For MegaDetector, there are only three categories: animal, human, and vehicle. For the opossum classification model, it only classifies animals between opossum and non-opossums. And for the Amazon rainforest classification model, it classifies 36 animal species. More details can be found in our summary paper: https://arxiv.org/pdf/2405.12930 , and we will be releasing more information on the training data in the future.

**Comment by zhmiao** [comment]
There is no further response since June. Therefore, we are closing this issue. If the issue still persist, please feel free to reopen it! Thank you so much for your participation!
