### ISSUE TITLE
Issue in result_generation method of yolov8_base.py

### ISSUE THREAD

**Issue by ayush2725** [microsoft/CameraTraps#523]
### Search before asking

- [X] I have searched the Pytorch-Wildlife [issues](https://github.com/microsoft/CameraTraps/issues) and found no similar bug report.

### Bug

In line 92 of the code, it's unpacking 5 objects but passing in 6, which is causing an exception to trigger on my device. I've attached an image of the exception for reference
![image](https://github.com/user-attachments/assets/2ea9fc2e-dc98-4d8c-8ad1-072bce3e5f84)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by danielaruizl1** [comment]
Hi @ayush2725, thank you for bringing this issue to our attention. The reported bug was due to changes in the supervision library when updated from version 0.16 to 0.19. We have already updated our code to be compatible, please ensure that you are using the most recent version of our codebase.
