### ISSUE TITLE
Yolov11 is not NMS-free

### ISSUE THREAD

**Issue by jdiaz97** [microsoft/CameraTraps#539]
Mentioned it on the discord, but leaving an issue here to keep track of it.

I'm pretty sure only YOLOv10 is NMS-free, and that YOLOv11 isn't.  I didn't find any documentation on Yolov11 being NMS-free.

If confirmed, I can submit a PR to edit the readme and/or docs

**Comment by zhmiao** [comment]
Hello @jdiaz97, thanks for bring this up! You are right! v11 does use nms and v10 does not. Since both are basically ultralytics models, maybe we should just include both! I will make changes to the readme to fix it.
