### ISSUE TITLE
CameraTraps/api/batch_processing/api_core/ readme not specific enough

### ISSUE THREAD

**Issue by abfleishman** [microsoft/CameraTraps#89]
I am attempting to set up the API in my own subscription and I have never used Azure Machine Learning workspace before. In the CameraTraps/api/batch_processing/api_core/README.md it states: to set up a new "AML workspace" but there are two resource types on azure that have similar names to this and it is not clear which I should use.  The two names are:
- `Azure Machine Learning service workspace`
- `Azure Machine Learning Studio workspace`

After reading the descriptions, I assume it is the `Azure Machine Learning service workspace` but I would like clarification.

**Comment by yangsiyu007** [comment]
Thanks for the feedback @abfleishman! You're right; we're referring to AML service. I've updated the readme with links to the service and instructions on setting up the workspace. For Step 2, please substitute [this](https://github.com/microsoft/AIforEarth-API-Development#dockerfile) Docker base image in the Dockerfile - we can get back to our email thread when you're ready to do that.
