### ISSUE TITLE
Error when image file is corrupted

### ISSUE THREAD

**Issue by matobler** [microsoft/CameraTraps#94]
Some images, especially from Bushnell cameras, are corrupted (there is missing data). An example is: Snapshot Serengeti\S1\I03\I03_R1\S1_I03_R1_PICT3967.JPG
The run_tf_detector_batch.py script crashes on those images. The only way to process the images is to open them in an image editor and save them again, replacing the bad data with some background value. 

Adding the following code to run_tf_detector_batch.py will replace the bad data automatically and allows the batch detector to run over all images without an error;

```python
from PIL import ImageFile
ImageFile.LOAD_TRUNCATED_IMAGES = True
```

**Comment by agentmorris** [comment]
Can you get latest from master and try again?  I'm a little hesitant to run the detector on truncated images without more extensive processing to decide *how* truncated they are (given unpredictability of the detector on heavily-truncated images), so instead we wrapped this in a try/except and did something reasonable with failed images (warning generated, no output written).  Want to make sure we've at least prevented annoying crashes, let us know if this works for you.

**Comment by matobler** [comment]
The new code prints an error message and skips over corrupt images. That's perfect. Thanks for addressing this.
